#!/bin/bash
clear
echo "******************************************************************************************"
k3d version
echo "****************************************************************************************** create cluster"
echo Run a K3D-K3S-Cluster: name $1 with $2 worker and $3 master nodes
k3d cluster create $1 --agents $2 --servers $3 --wait --timeout 200s --api-port 127.0.0.1:6444 
echo "****************************************************************************************** KUBECONFIG"
# export KUBECONFIG="$(k3d kubeconfig get $1)"
k3d kubeconfig get $1
echo "OK"
echo "****************************************************************************************** docker ps"
docker ps
echo "****************************************************************************************** cluster-info"
k3d cluster list
kubectl cluster-info
sleep 10	
echo "****************************************************************************************** get nodes"
kubectl get nodes -o wide
sleep 45
echo "****************************************************************************************** get pods --all-namespaces"
kubectl get pods --all-namespaces -o wide
echo "****************************************************************************************** get deployments --all-namespaces"
kubectl get deployments --all-namespaces -o wide
echo "****************************************************************************************** kubectl create/run"
kubectl create deployment nginx --image=bitnami/nginx
kubectl run --generator=run-pod/v1 mycountry --image=zoobab/country
sleep 45
echo "****************************************************************************************** get deployments --all-namespaces"
kubectl get deployments --all-namespaces -o wide
echo "****************************************************************************************** get pods --all-namespaces"
kubectl get pods --all-namespaces -o wide
echo "****************************************************************************************** kubectl logs"
kubectl logs $(kubectl get pods -o name --namespace default|grep nginx) > ./nginx.log
echo "kubectl logs nginx > ./nginx.log"
kubectl logs mycountry > ./mycountry.log
echo "kubectl logs mycountry > ./mycountry.log"
echo "****************************************************************************************** cat ./mycontry.log"
cat ./mycountry.log
echo "****************************************************************************************** cat ./nginx.log"
cat ./nginx.log
echo "****************************************************************************************** k3d delete"
# k3d --verbose delete -name $1
echo "****************************************************************************************** k3d list"
k3d cluster list
echo "****************************************************************************************** end"
